spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  jwt:
    secret: QrDgivheiBAokY32EdpmqoleefAy3pQc1ff9sCxe
    expiration_time: 86400000 #1일

scrap:
  url: https://codetest-v4.3o3.co.kr/scrap
  x-api-key: fQL4PtoGRRgj6Q1OZG1WpQ==

springdoc:
  swagger-ui:
    path: /3o3/swagger.html
